### ISSUE TITLE
getPreviousPage not working with pathFor on routes with parameters

### ISSUE THREAD

**Issue by molleman** [zendylabs/velociratchet-meteor-package#1]
I'm having Trouble with adding to the history if the current route has a parameter such as 

`http://localhost:3000/categories/njHT6EaGcasGhyLvs` 

`Router.current().route.getName()` only retrieves `categories` for the `getPreviousPage` which is then failing at the `pathFor` helper.

**Comment by yacinemerzouk** [comment]
Hi there,

That's a good point. We'll look at that when we get a chance. Probably next week though.
